// src/environments/runtime-env.ts
// AUTO-GENERATED. Do not edit directly.
// Generated by scripts/generate-runtime-env.mjs

export const runtimeEnv = {
  googleMapsApiKey: "AIzaSyDZxmBZAxfNIgOr5gp_d1eNqvcKzBHTUbE",
};
